/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BilingualText { 'en' : string, 'hi' : string }
export interface PersonalityType {
  'weaknesses' : Array<BilingualText>,
  'strengths' : Array<BilingualText>,
  'code' : string,
  'name' : BilingualText,
  'negative' : Array<BilingualText>,
  'description' : BilingualText,
  'likes' : Array<BilingualText>,
  'balanceTips' : BilingualText,
  'positive' : Array<BilingualText>,
  'dislikes' : Array<BilingualText>,
}
export interface QuizQuestion {
  'question' : BilingualText,
  'answerAEI' : BilingualText,
  'answerBEI' : BilingualText,
  'answerA' : BilingualText,
  'answerB' : BilingualText,
  'answerAJPL' : BilingualText,
  'answerASNL' : BilingualText,
  'answerATFL' : BilingualText,
  'answerBJPL' : BilingualText,
  'answerBSNL' : BilingualText,
  'answerBTFL' : BilingualText,
}
export interface _SERVICE {
  'getAllPersonalityTypes' : ActorMethod<[], Array<PersonalityType>>,
  'getAllQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getPersonalityType' : ActorMethod<[string], PersonalityType>,
  'initialize' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];