/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BilingualText = IDL.Record({ 'en' : IDL.Text, 'hi' : IDL.Text });
export const PersonalityType = IDL.Record({
  'weaknesses' : IDL.Vec(BilingualText),
  'strengths' : IDL.Vec(BilingualText),
  'code' : IDL.Text,
  'name' : BilingualText,
  'negative' : IDL.Vec(BilingualText),
  'description' : BilingualText,
  'likes' : IDL.Vec(BilingualText),
  'balanceTips' : BilingualText,
  'positive' : IDL.Vec(BilingualText),
  'dislikes' : IDL.Vec(BilingualText),
});
export const QuizQuestion = IDL.Record({
  'question' : BilingualText,
  'answerAEI' : BilingualText,
  'answerBEI' : BilingualText,
  'answerA' : BilingualText,
  'answerB' : BilingualText,
  'answerAJPL' : BilingualText,
  'answerASNL' : BilingualText,
  'answerATFL' : BilingualText,
  'answerBJPL' : BilingualText,
  'answerBSNL' : BilingualText,
  'answerBTFL' : BilingualText,
});

export const idlService = IDL.Service({
  'getAllPersonalityTypes' : IDL.Func(
      [],
      [IDL.Vec(PersonalityType)],
      ['query'],
    ),
  'getAllQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getPersonalityType' : IDL.Func([IDL.Text], [PersonalityType], ['query']),
  'initialize' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BilingualText = IDL.Record({ 'en' : IDL.Text, 'hi' : IDL.Text });
  const PersonalityType = IDL.Record({
    'weaknesses' : IDL.Vec(BilingualText),
    'strengths' : IDL.Vec(BilingualText),
    'code' : IDL.Text,
    'name' : BilingualText,
    'negative' : IDL.Vec(BilingualText),
    'description' : BilingualText,
    'likes' : IDL.Vec(BilingualText),
    'balanceTips' : BilingualText,
    'positive' : IDL.Vec(BilingualText),
    'dislikes' : IDL.Vec(BilingualText),
  });
  const QuizQuestion = IDL.Record({
    'question' : BilingualText,
    'answerAEI' : BilingualText,
    'answerBEI' : BilingualText,
    'answerA' : BilingualText,
    'answerB' : BilingualText,
    'answerAJPL' : BilingualText,
    'answerASNL' : BilingualText,
    'answerATFL' : BilingualText,
    'answerBJPL' : BilingualText,
    'answerBSNL' : BilingualText,
    'answerBTFL' : BilingualText,
  });
  
  return IDL.Service({
    'getAllPersonalityTypes' : IDL.Func(
        [],
        [IDL.Vec(PersonalityType)],
        ['query'],
      ),
    'getAllQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getPersonalityType' : IDL.Func([IDL.Text], [PersonalityType], ['query']),
    'initialize' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };